backend:
  name: github
  repo: rodinshrestha/kitchen-v2
  branch: main

publish_mode: editorial_workflow
media_folder: "static/uploads"
public_folder: /uploads

collections:
  - name: "starter_salad"
    label: "Starter and Salad"
    folder: "/content/kitchen_menu/starter_salad"
    create: true
    slug: "{{day}}-{{month}}-{{year}}-{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Price", name: "price", widget: "string" }

  - name: "momo"
    label: "MoMo - Steamed Dumplings"
    folder: "/content/kitchen_menu/momo"
    create: true
    slug: "{{day}}-{{month}}-{{year}}-{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Price", name: "price", widget: "string" }

  - name: "curry_dishes"
    label: "Curry Dishes"
    folder: "/content/kitchen_menu/curry_dishes"
    create: true
    slug: "{{day}}-{{month}}-{{year}}-{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Price", name: "price", widget: "string" }

  - name: "tandoori"
    label: "Tandoori"
    folder: "/content/kitchen_menu/tandoori"
    create: true
    slug: "{{day}}-{{month}}-{{year}}-{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Price", name: "price", widget: "string" }

  - name: "tika_masala"
    label: "Tika Masala"
    folder: "/content/kitchen_menu/tika_masala"
    create: true
    slug: "{{day}}-{{month}}-{{year}}-{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Price", name: "price", widget: "string" }

  - name: "sides"
    label: "Sides"
    folder: "/content/kitchen_menu/sides"
    create: true
    slug: "{{day}}-{{month}}-{{year}}-{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Price", name: "price", widget: "string" }

  #######################
  # Drinks Menu list
  #######################

  - name: "sparkling_wines"
    label: "Sparkling Wines"
    folder: "/content/drinks_menu/sparkling_wines"
    create: true
    slug: "{{day}}-{{month}}-{{year}}-{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Price", name: "price", widget: "string" }

  - name: "white_wines"
    label: "White Wines"
    folder: "/content/drinks_menu/white_wines"
    create: true
    slug: "{{day}}-{{month}}-{{year}}-{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Price", name: "price", widget: "string" }

  - name: "red_wines"
    label: "Red Wines"
    folder: "/content/drinks_menu/red_wines"
    create: true
    slug: "{{day}}-{{month}}-{{year}}-{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Price", name: "price", widget: "string" }

  - name: "beer"
    label: "Beer"
    folder: "/content/drinks_menu/beer"
    create: true
    slug: "{{day}}-{{month}}-{{year}}-{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Price", name: "price", widget: "string" }

  - name: "beverages"
    label: "Beverages"
    folder: "/content/drinks_menu/beverages"
    create: true
    slug: "{{day}}-{{month}}-{{year}}-{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Price", name: "price", widget: "string" }

  - name: "gallery"
    label: "Gallery"
    folder: "/content/gallery"
    create: true
    slug: "{{day}}-{{month}}-{{year}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }

  #######################
  # Website Settings
  #######################

  - name: "settings"
    label: "Settings"
    files:
      - label: "Settings File"
        name: "settings_file"
        file: "content/settings/settings.json"
        fields:
          - label: "Footer Text"
            name: "footer_text"
            widget: "string"

          - label: "Phone Number"
            name: "phone_number"
            widget: "string"

          - label: "Email"
            name: "email"
            widget: "string"

          - label: "Hero Banner Text"
            name: "hero_banner_text"
            widget: "string"

          - label: "Lunch Time"
            name: "lunch_time"
            widget: "string"

          - label: "Lunch last seated Time"
            name: "lunch_last_seated_time"
            widget: "string"

          - label: "Dinner Time"
            name: "dinner_time"
            widget: "string"

          - label: "Dinner last seated Time"
            name: "dinner_last_seated_time"
            widget: "string"

          - label: "Story"
            name: "story_content"
            widget: "markdown"

          - label: "About us"
            name: "about_us"
            widget: "markdown"

  #######################
  # Blog Details
  #######################

  - name: "blog"
    label: "Blog"
    folder: "/content/blog"
    create: true
    slug: "{{day}}-{{month}}-{{year}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Description", name: "description", widget: "markdown" }

  #######################
  # Everest trek details
  #######################

  - name: "everest-trek"
    label: "Everest Base Camp Trek"
    folder: "/content/everest_base_camp_trek"
    # create: true
    # slug: "{{day}}-{{month}}-{{year}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Description", name: "description", widget: "markdown" }
